<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Booktype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Booktype_model');
    } 

    /*
     * Listing of booktypes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('booktype/index?');
        $config['total_rows'] = $this->Booktype_model->get_all_booktypes_count();
        $this->pagination->initialize($config);

        $data['booktypes'] = $this->Booktype_model->get_all_booktypes($params);
        
        $data['_view'] = 'booktype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new booktype
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		$this->form_validation->set_rules('code','Code','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'code' => $this->input->post('code'),
            );
            
            $booktype_id = $this->Booktype_model->add_booktype($params);
            redirect('booktype/index');
        }
        else
        {            
            $data['_view'] = 'booktype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a booktype
     */
    function edit($id)
    {   
        // check if the booktype exists before trying to edit it
        $data['booktype'] = $this->Booktype_model->get_booktype($id);
        
        if(isset($data['booktype']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('code','Code','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'code' => $this->input->post('code'),
                );

                $this->Booktype_model->update_booktype($id,$params);            
                redirect('booktype/index');
            }
            else
            {
                $data['_view'] = 'booktype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The booktype you are trying to edit does not exist.');
    } 

    /*
     * Deleting booktype
     */
    function remove($id)
    {
        $booktype = $this->Booktype_model->get_booktype($id);

        // check if the booktype exists before trying to delete it
        if(isset($booktype['id']))
        {
            $this->Booktype_model->delete_booktype($id);
            redirect('booktype/index');
        }
        else
            show_error('The booktype you are trying to delete does not exist.');
    }
    
}
