<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Booksinn extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Booksinn_model');
    } 

    /*
     * Listing of booksinn
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('booksinn/index?');
        $config['total_rows'] = $this->Booksinn_model->get_all_booksinn_count();
        $this->pagination->initialize($config);

        $data['booksinn'] = $this->Booksinn_model->get_all_booksinn($params);
        
        $data['_view'] = 'booksinn/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new booksinn
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('inn','Inn','required');
		$this->form_validation->set_rules('books_id','Books Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'books_id' => $this->input->post('books_id'),
				'inn' => $this->input->post('inn'),
            );
            
            $booksinn_id = $this->Booksinn_model->add_booksinn($params);
            redirect('booksinn/index');
        }
        else
        {
			$this->load->model('Book_model');
			$data['all_books'] = $this->Book_model->get_all_books();
            
            $data['_view'] = 'booksinn/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a booksinn
     */
    function edit($id)
    {   
        // check if the booksinn exists before trying to edit it
        $data['booksinn'] = $this->Booksinn_model->get_booksinn($id);
        
        if(isset($data['booksinn']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('inn','Inn','required');
			$this->form_validation->set_rules('books_id','Books Id','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'books_id' => $this->input->post('books_id'),
					'inn' => $this->input->post('inn'),
                );

                $this->Booksinn_model->update_booksinn($id,$params);            
                redirect('booksinn/index');
            }
            else
            {
				$this->load->model('Book_model');
				$data['all_books'] = $this->Book_model->get_all_books();

                $data['_view'] = 'booksinn/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The booksinn you are trying to edit does not exist.');
    } 

    /*
     * Deleting booksinn
     */
    function remove($id)
    {
        $booksinn = $this->Booksinn_model->get_booksinn($id);

        // check if the booksinn exists before trying to delete it
        if(isset($booksinn['id']))
        {
            $this->Booksinn_model->delete_booksinn($id);
            redirect('booksinn/index');
        }
        else
            show_error('The booksinn you are trying to delete does not exist.');
    }

    function getbooksinn($id){
        $books = $this->Booksinn_model->get_bookinn_by_book($id);
        echo"
        <select name=\"booksinn\" class=\"form-control\" id=\"bookss\"  onchange=\"loadbooksok()\">
                            <option value=\"\">--номер книги--</option>
        ";
        foreach ($books as $v){


            echo '<option value="'.$v['id'].'" >'.$v['inn'].'</option>';
        }

        echo"  </select>";

    }


}
