<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Book extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Book_model');
    }

    /*
     * Listing of books
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('book/index?');
        $config['total_rows'] = $this->Book_model->get_all_books_count();
        $this->pagination->initialize($config);

        $data['books'] = $this->Book_model->get_all_books($params);

        $data['_view'] = 'book/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new book
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('publishhouse','Publishhouse','required');
        $this->form_validation->set_rules('name','Name','required');
        $this->form_validation->set_rules('publishdate','Publishdate','required');
        $this->form_validation->set_rules('booktypes_id','Booktypes Id','required');

        if($this->form_validation->run())
        {
            $params = array(
                'booktypes_id' => $this->input->post('booktypes_id'),
                'name' => $this->input->post('name'),
                'publishdate' => $this->input->post('publishdate'),
                'publishhouse' => $this->input->post('publishhouse'),
            );

            $book_id = $this->Book_model->add_book($params);
            redirect('book/index');
        }
        else
        {
            $this->load->model('Booktype_model');
            $data['all_booktypes'] = $this->Booktype_model->get_all_booktypes();

            $data['_view'] = 'book/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a book
     */
    function edit($id)
    {
        // check if the book exists before trying to edit it
        $data['book'] = $this->Book_model->get_book($id);

        if(isset($data['book']['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('publishhouse','Publishhouse','required');
            $this->form_validation->set_rules('name','Name','required');
            $this->form_validation->set_rules('publishdate','Publishdate','required');
            $this->form_validation->set_rules('booktypes_id','Booktypes Id','required');

            if($this->form_validation->run())
            {
                $params = array(
                    'booktypes_id' => $this->input->post('booktypes_id'),
                    'name' => $this->input->post('name'),
                    'publishdate' => $this->input->post('publishdate'),
                    'publishhouse' => $this->input->post('publishhouse'),
                );

                $this->Book_model->update_book($id,$params);
                redirect('book/index');
            }
            else
            {
                $this->load->model('Booktype_model');
                $data['all_booktypes'] = $this->Booktype_model->get_all_booktypes();

                $data['_view'] = 'book/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The book you are trying to edit does not exist.');
    }

    /*
     * Deleting book
     */
    function remove($id)
    {
        $book = $this->Book_model->get_book($id);

        // check if the book exists before trying to delete it
        if(isset($book['id']))
        {
            $this->Book_model->delete_book($id);
            redirect('book/index');
        }
        else
            show_error('The book you are trying to delete does not exist.');
    }

    public function getbooks($id){
        $books = $this->Book_model->get_book_by_type($id);
        echo"
        <select name=\"booktypes_id\" class=\"form-control\" id=\"bookss\"  onchange=\"loadbooksinn()\">
                            <option value=\"\">--книги--</option>
        ";
        foreach ($books as $v){


            echo '<option value="'.$v['id'].'" >'.$v['name'].'</option>';
        }

        echo"  </select>";
    }

}
