<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $this->load->model('Book_model');
        $data['countbooktype'] = $this->Book_model->get_all_books_count();

        $this->load->model('Booksinn_model');
        $data['countbookinn'] = $this->Booksinn_model->get_all_booksinn_count();

        $this->load->model('User_model');
        $data['countuser'] = $this->User_model->get_all_users_count();
        $this->load->model('Card_model');
        $data['counthistory'] = $this->Card_model->get_all_card_count();

        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
