<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Booktype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get booktype by id
     */
    function get_booktype($id)
    {
        return $this->db->get_where('booktypes',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all booktypes count
     */
    function get_all_booktypes_count()
    {
        $this->db->from('booktypes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all booktypes
     */
    function get_all_booktypes($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('booktypes')->result_array();
    }
        
    /*
     * function to add new booktype
     */
    function add_booktype($params)
    {
        $this->db->insert('booktypes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update booktype
     */
    function update_booktype($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('booktypes',$params);
    }
    
    /*
     * function to delete booktype
     */
    function delete_booktype($id)
    {
        return $this->db->delete('booktypes',array('id'=>$id));
    }
}
